[package]
name = "planetkit"
version = "0.0.1"
authors = ["Jeff Parsons <jeff@parsons.io>"]
build = "build.rs"

[features]
nightly = []

[lib]
path = "src/lib.rs"

[[bin]]
name = "demo"
path = "src/bin/main.rs"

[dependencies]
noise = "0.4.0"
piston = "0.32.0"
piston2d-graphics = "0.21.1"
pistoncore-glutin_window = "0.37.0"
piston2d-opengl_graphics = "0.43.0"
gfx = "0.16.0"
gfx_device_gl = "0.14.0"
piston_window = "0.66.0"
camera_controllers = "0.21.0"
vecmath = "0.3.0"
shader_version = "0.2.1"
nalgebra = "0.12.2"
rand = "0.3.14"
slog = "2.0.4"
slog-term = "2.0.0"
slog-async = "2.0.1"
chrono = "0.3.0"
shred = "0.4.1"
specs = "0.9.0"
num-traits = "0.1.36"
itertools = "0.6.0"
# At time of writing, only used for tests.
approx = "0.1.1"
froggy = "0.3.0"
arrayvec = "0.3.23"
futures = "0.1.14"
tokio-core = "0.1.8"
serde = "1.0.10"
serde_json = "1.0.2"
serde_derive = "1.0.10"

[build-dependencies]
rustc_version = "0.2.1"
