[package]
name = "planetkit"
version = "0.0.1"
authors = ["Jeff Parsons <jeff@parsons.io>"]
build = "build.rs"

[features]
nightly = []
web = []
default = ["desktop"]
# All the stuff that won't work on the web.
desktop = ["tokio-core", "tokio-io"]

[lib]
path = "src/lib.rs"

[[bin]]
name = "demo"
path = "src/bin/main.rs"

[dependencies]
bytes = "0.4.5"
noise = "0.4.0"
piston = "0.35.0"
piston2d-graphics = "0.23.0"
pistoncore-glutin_window = "0.42.0"
piston2d-opengl_graphics = "0.49.0"
gfx = "0.16.0"
gfx_device_gl = "0.14.0"
piston_window = "0.73.0"
camera_controllers = "0.23.0"
vecmath = "0.3.0"
shader_version = "0.3.0"
nalgebra = "0.13.0"
rand = "0.3.14"
slog = "2.0.4"
slog-term = "2.0.0"
slog-async = "2.0.1"
chrono = "0.4.0"
shred = "0.5.0"
specs = "0.10.0"
num-traits = "0.1.36"
itertools = "0.7.1"
# At time of writing, only used for tests.
approx = "0.1.1"
froggy = "0.4.0"
arrayvec = "0.4.5"
futures = "0.1.14"
serde = "1.0.10"
serde_json = "1.0.2"
serde_derive = "1.0.10"

# Stuff we can't run on the web yet.
tokio-core = { version = "0.1.8", optional = true }
tokio-io = { version = "0.1.3", optional = true }

[build-dependencies]
rustc_version = "0.2.1"
