[package]
name = "planetkit"
version = "0.1.0"
authors = ["Jeff Parsons <jeff@parsons.io>"]

[dependencies]
noise = "0.2.0"
piston = "0.25.1"
piston2d-graphics = "0.17.0"
pistoncore-glutin_window = "0.30.0"
piston2d-opengl_graphics = "0.33.0"
