[package]
name = "planetkit"
version = "0.0.1"
authors = ["Jeff Parsons <jeff@parsons.io>"]

[lib]
path = "src/lib.rs"

[dependencies]
noise = "0.2.0"
piston = "0.25.1"
piston2d-graphics = "0.17.0"
pistoncore-glutin_window = "0.30.0"
piston2d-opengl_graphics = "0.33.0"
gfx = "0.12.1"
gfx_device_gl = "0.11.2"
piston_window = "0.53.0"
camera_controllers = "0.17.0"
vecmath = "0.2.0"
shader_version = "0.2.1"
nalgebra = "0.10.1"
rand = "0.3.14"
slog = "1.3.2"
slog-term = "1.3.3"
chrono = "0.2"
specs = "0.7.0"
num-traits = "0.1.36"
