[workspace]
members = [
    # Main PlanetKit crate
    "planetkit",
    # Example single-player game involving rescuing sheep that have fallen into holes
    "woolgather",
    # Example multi-player game involving shooting each other with explosive weapons
    "kaboom",
]
