[package]
name = "woolgather"
version = "0.0.1"
authors = ["Jeff Parsons <jeff@parsons.io>"]

[dependencies]
planetkit = { path = "../planetkit" }
rand = "0.3.14"
shred = "0.5.0"
specs = "0.10.0"
slog = "2.0.4"
